-- Sample Users
insert into user (
   user_id,
   first_name,
   last_name,
   email,
   password_hash,
   phone_number,
   role,
   created_at
) values ( uuid(),
           'John',
           'Doe',
           'john.doe@example.com',
           'hashedpassword1',
           '123-456-7890',
           'guest',
           current_timestamp ),( uuid(),
                                 'Alice',
                                 'Smith',
                                 'alice.smith@example.com',
                                 'hashedpassword2',
                                 '987-654-3210',
                                 'host',
                                 current_timestamp ),( uuid(),
                                                       'Bob',
                                                       'Johnson',
                                                       'bob.johnson@example.com',
                                                       'hashedpassword3',
                                                       '456-789-0123',
                                                       'admin',
                                                       current_timestamp ),( uuid(),
                                                                             'Emily',
                                                                             'Davis',
                                                                             'emily.davis@example.com',
                                                                             'hashedpassword4',
                                                                             '321-654-9870',
                                                                             'guest',
                                                                             current_timestamp );

-- Sample Properties
insert into property (
   property_id,
   host_id,
   name,
   description,
   location,
   pricepernight,
   created_at,
   updated_at
) values ( uuid(),
           'host-uuid-1',
           'Cozy Apartment in Downtown',
           'A modern 2-bedroom apartment with city views.',
           'New York, NY',
           150.00,
           current_timestamp,
           current_timestamp ),( uuid(),
                                 'host-uuid-2',
                                 'Beachfront Villa',
                                 'A luxurious 5-bedroom villa right on the beach.',
                                 'Miami, FL',
                                 500.00,
                                 current_timestamp,
                                 current_timestamp ),( uuid(),
                                                       'host-uuid-1',
                                                       'Mountain Cabin',
                                                       'A secluded cabin with stunning mountain views.',
                                                       'Aspen, CO',
                                                       200.00,
                                                       current_timestamp,
                                                       current_timestamp );

-- Sample Bookings
insert into booking (
   booking_id,
   property_id,
   user_id,
   start_date,
   end_date,
   total_price,
   status,
   created_at
) values ( uuid(),
           'property-uuid-1',
           'user-uuid-1',
           '2024-12-10',
           '2024-12-15',
           750.00,
           'confirmed',
           current_timestamp ),( uuid(),
                                 'property-uuid-2',
                                 'user-uuid-4',
                                 '2024-12-20',
                                 '2024-12-25',
                                 2500.00,
                                 'pending',
                                 current_timestamp ),( uuid(),
                                                       'property-uuid-3',
                                                       'user-uuid-1',
                                                       '2024-12-25',
                                                       '2024-12-30',
                                                       1000.00,
                                                       'confirmed',
                                                       current_timestamp );

-- Sample Payments
insert into payment (
   payment_id,
   booking_id,
   amount,
   payment_date,
   payment_method
) values ( uuid(),
           'booking-uuid-1',
           750.00,
           current_timestamp,
           'credit_card' ),( uuid(),
                             'booking-uuid-3',
                             1000.00,
                             current_timestamp,
                             'paypal' );

-- Sample Reviews
insert into review (
   review_id,
   property_id,
   user_id,
   rating,
   comment,
   created_at
) values ( uuid(),
           'property-uuid-1',
           'user-uuid-1',
           5,
           'Amazing stay! The apartment was perfect and had great views.',
           current_timestamp ),( uuid(),
                                 'property-uuid-2',
                                 'user-uuid-4',
                                 4,
                                 'Beautiful villa with an amazing beach. Only downside was the Wi-Fi.',
                                 current_timestamp ),( uuid(),
                                                       'property-uuid-3',
                                                       'user-uuid-1',
                                                       5,
                                                       'The cabin was peaceful and perfect for a winter getaway.',
                                                       current_timestamp );

-- Sample Messages
insert into message (
   message_id,
   sender_id,
   recipient_id,
   message_body,
   sent_at
) values ( uuid(),
           'user-uuid-1',
           'user-uuid-4',
           'Hi Alice, I’d love to book the beachfront villa for my family this Christmas!',
           current_timestamp ),( uuid(),
                                 'user-uuid-4',
                                 'user-uuid-1',
                                 'Sure! The villa is available, and I look forward to hosting you!',
                                 current_timestamp ),( uuid(),
                                                       'user-uuid-1',
                                                       'user-uuid-2',
                                                       'I would like to know more about the cabin availability for New Year’s Eve.'
                                                       ,
                                                       current_timestamp );